#!/usr/bin/env bash
# PreToolUse (Edit|Write|MultiEdit): refuse hand edits to generated paths.
# Exit 2 sends the message back to Claude and cancels the edit.
set -u
here="$(cd "$(dirname "$0")" && pwd)"
file="$(python3 "$here/_input.py" file_path)"
[ -n "$file" ] || exit 0
root="${CLAUDE_PROJECT_DIR:-$(pwd)}"
rel="${file#"$root"/}"
case "$rel" in
  apps/web/pkg/*)
    echo "apps/web/pkg/ is generated by \`make wasm\` from crates/auracle-wasm. Change the Rust, then rebuild." >&2; exit 2 ;;
  site/*)
    echo "site/ is assembled by \`make site\` from www/. Edit the source under www/ instead." >&2; exit 2 ;;
  target/*)
    echo "target/ is cargo's build output; nothing there is edited by hand." >&2; exit 2 ;;
  www/docs/src/img/*)
    echo "www/docs/src/img/ is a build-time copy of www/landing/assets/screens/. Edit or recapture the source (see www/SCREENSHOTS.md)." >&2; exit 2 ;;
  www/landing/assets/film/*)
    echo "www/landing/assets/film/ is written by www/video/tools/publish.py. Re-render or re-publish the film instead." >&2; exit 2 ;;
esac
exit 0
