#!/usr/bin/env python3
"""The release script's tests (`scripts/release.py`): how a squash subject
reads as a title, the version the titles call for, the bump and where it
writes, what a tag owes, the list of what merged by type, the release PR's
body, and the command on a scratch repository.

    python3 scripts/test_release.py      (run by `make dev-check`)

No test reaches the network: the authors come from a fake API. No test
writes the real tree: each builds a throwaway one in a temp dir, and the
cases about history commit and tag in a scratch git repo there, with no
GIT_* variable from the caller (a hook's GIT_DIR would point git at this
repository) and no global or system config. The last cases read the real
workspace, and bump a copy of it. Python 3 standard library only.
"""

import contextlib
import io
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import changelog as C  # noqa: E402
import pr_checks as P  # noqa: E402
import release as R  # noqa: E402

TMP = pathlib.Path(tempfile.gettempdir()).resolve()

CARGO = """[workspace]
resolver = "2"
members = [
    "crates/auracle-a",
    "crates/auracle-b",
]

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.dependencies]
quiver-dsp = "0.2.0"
serde = { version = "1", features = ["derive"] }

# Intra-workspace
auracle-a = { path = "crates/auracle-a", version = "0.2.0" }
# auracle-b = { path = "crates/auracle-b", version = "0.2.0" }
"""

CRATE_A = """[package]
name = "auracle-a"
version.workspace = true

[dependencies]
quiver-dsp.workspace = true
"""

CRATE_B = """[package]
name = "auracle-b"
version.workspace = true

[dependencies]
auracle-a = { path = "../auracle-a", version = "0.2.0" }
fugue = { version = "0.2.0", features = ["x"] }
"""

LOCK = """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "auracle-a"
version = "0.2.0"
dependencies = [
 "quiver-dsp",
]

[[package]]
name = "auracle-b"
version = "0.2.0"
dependencies = [
 "auracle-a",
 "fugue",
]

[[package]]
name = "auracle-b"
version = "0.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "quiver-dsp"
version = "0.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""

CHANGELOG = f"""# Changelog

## [Unreleased]

{C.NOTE}

## [0.3.0] - 2026-10-06

The release, in a paragraph.

### Fixed: a thing

- **It works.**

## [0.2.0] - 2026-08-04

### Added: the rest

- **More.**
"""


def git_env():
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    env.update(GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_NOSYSTEM="1", GIT_CEILING_DIRECTORIES=str(TMP))
    return env


class Tree:
    """A throwaway workspace: two crates, a lock, a changelog at 0.3.0 and
    changelog.d/ with its README; with `git=True`, a scratch repo too."""

    def __init__(self, git=False):
        self.git_ = git

    def __enter__(self):
        self.root = pathlib.Path(tempfile.mkdtemp(prefix="release-", dir=TMP))
        self.write("Cargo.toml", CARGO)
        self.write("crates/auracle-a/Cargo.toml", CRATE_A)
        self.write("crates/auracle-b/Cargo.toml", CRATE_B)
        self.write("Cargo.lock", LOCK)
        self.write("CHANGELOG.md", CHANGELOG)
        self.write("changelog.d/README.md", "# changelog.d\n")
        if self.git_:
            self.git("init", "-q", "-b", "main", ".")
        return self

    def __exit__(self, *exc):
        shutil.rmtree(self.root)

    def write(self, rel, text):
        p = self.root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")

    def text(self, rel):
        return (self.root / rel).read_text(encoding="utf-8")

    def git(self, *args):
        ident = ["-c", "user.name=Release Test", "-c", "user.email=release-test@example.invalid", "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false"]
        subprocess.run(["git", *ident, *args], cwd=self.root, env=git_env(), check=True, capture_output=True)

    def commit(self, subject):
        self.git("add", "-A")
        self.git("commit", "-q", "--allow-empty", "-m", subject)

    def run(self, *argv, get=None):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = R.main(list(argv), self.root, get or refuse_network)
        return code, out.getvalue(), err.getvalue()


def refuse_network(url):
    raise AssertionError(f"no test reaches the network: {url}")


def titles(*subjects):
    return [R.read_subject(s) for s in subjects]


class Api:
    """The closed PRs, numbered 1 to `top`, newest first a page at a time,
    each by `who(n)`; it counts the calls."""

    def __init__(self, top, who=lambda n: {"login": f"user{n % 3}"}, missing=()):
        self.top, self.who, self.missing, self.calls = top, who, set(missing), []

    def __call__(self, url):
        self.calls.append(url)
        if "/pulls/" in url:
            n = int(url.rsplit("/", 1)[1])
            return {"number": n, "user": self.who(n)}
        page = int(url.rsplit("page=", 1)[1])
        numbers = [n for n in range(self.top, 0, -1) if n not in self.missing]
        chunk = numbers[(page - 1) * R.PAGE : page * R.PAGE]
        return [{"number": n, "user": self.who(n)} for n in chunk]


# ─── titles and versions ─────────────────────────────────────────────────────


class ASubject(unittest.TestCase):
    def test_is_the_title_its_type_and_the_number_the_queue_appended(self):
        t = R.read_subject("fix(web): a toast is never dropped (#212)")
        self.assertEqual(t, R.Title(212, "fix(web): a toast is never dropped", "fix", False))

    def test_a_bang_after_the_type_is_breaking(self):
        self.assertTrue(R.read_subject("feat(engine)!: seeds deal differently (#3)").breaking)
        self.assertTrue(R.read_subject("refactor!: one stream (#4)").breaking)
        self.assertFalse(R.read_subject("feat: a thing! (#5)").breaking)

    def test_a_type_pr_checks_does_not_accept_is_no_type(self):
        for s in ("PATCH: a sound fades up (#230)", "CI: read the channel (#125)", "A toast has its turn (#220)", 'Revert "feat: x" (#9)', "PATCH!: loud (#1)"):
            t = R.read_subject(s)
            self.assertEqual((t.type, t.breaking), (None, False), s)

    def test_only_the_number_at_the_end_is_the_prs(self):
        t = R.read_subject("PATCH's specs; #120, #127 fixed and back (#168)")
        self.assertEqual((t.number, t.title), (168, "PATCH's specs; #120, #127 fixed and back"))
        self.assertEqual(R.read_subject("fix: pushed by hand").number, None)


class TheVersion(unittest.TestCase):
    def level(self, *subjects, major=0):
        return R.level_for(titles(*subjects), major)[0]

    def test_a_feat_is_minor_a_fix_or_perf_a_patch(self):
        self.assertEqual(self.level("fix: a (#1)", "feat(web): b (#2)", "docs: c (#3)"), "minor")
        self.assertEqual(self.level("fix: a (#1)", "docs: c (#3)"), "patch")
        self.assertEqual(self.level("perf(web): a (#1)"), "patch")

    def test_a_breaking_change_moves_the_minor_while_the_major_is_0(self):
        self.assertEqual(self.level("fix!: a (#1)"), "minor")
        self.assertEqual(self.level("fix!: a (#1)", major=1), "major")
        self.assertEqual(self.level("feat: a (#1)", major=1), "minor")

    def test_anything_else_alone_is_a_patch_and_says_so(self):
        level, why = R.level_for(titles("docs: a (#1)", "PATCH: b (#2)", "ci: c (#3)"), 0)
        self.assertEqual(level, "patch")
        self.assertIn("no feat, fix, perf or breaking", why)

    def test_a_bump_resets_the_numbers_below_it(self):
        self.assertEqual(R.bumped("1.4.2", "major"), "2.0.0")
        self.assertEqual(R.bumped("1.4.2", "minor"), "1.5.0")
        self.assertEqual(R.bumped("1.4.2", "patch"), "1.4.3")
        self.assertEqual(R.bumped("0.2.0", "minor"), "0.3.0")

    def test_the_last_tag_is_the_highest_release_by_number(self):
        tags = ["v0.9.0", "v0.10.0", "v0.2.0", "v1.0.0-rc1", "vfoo", "0.11.0", "v0.12"]
        self.assertEqual(R.last_tag(tags), "v0.10.0")
        self.assertIsNone(R.last_tag(["latest", "nightly"]))

    def test_counts_go_by_type_then_the_untyped(self):
        got = R.counts(titles("PATCH: x (#1)", "fix: a (#2)", "feat: b (#3)", "fix: c (#4)", "release: 0.2.0 (#5)"))
        self.assertEqual(got, [("feat", 1), ("fix", 2), ("release", 1), ("without a type", 1)])


class TheDecision(unittest.TestCase):
    FEAT = titles("feat(web): a (#10)", "fix: b (#11)")

    def test_the_titles_since_the_last_tag_pick_the_version(self):
        plan = R.decide("v0.2.0", "0.2.0", None, self.FEAT)
        self.assertEqual((plan.version, plan.computed, plan.level, plan.folded), ("0.3.0", "0.3.0", "minor", False))

    def test_a_version_asked_for_wins_when_it_is_above_the_last(self):
        plan = R.decide("v0.2.0", "0.2.0", None, self.FEAT, "1.0.0")
        self.assertEqual((plan.version, plan.computed), ("1.0.0", "0.3.0"))
        for asked in ("0.2.0", "0.1.9"):
            with self.assertRaisesRegex(R.Refused, "not above the last release, v0.2.0"):
                R.decide("v0.2.0", "0.2.0", None, self.FEAT, asked)
        with self.assertRaisesRegex(R.Refused, "not a version"):
            R.decide("v0.2.0", "0.2.0", None, self.FEAT, "v0.3.0")

    def test_nothing_merged_is_refused(self):
        with self.assertRaisesRegex(R.Refused, "nothing has merged since v0.2.0"):
            R.decide("v0.2.0", "0.2.0", None, [])

    def test_a_workspace_bumped_by_hand_is_refused(self):
        with self.assertRaisesRegex(R.Refused, "says 0.2.5 and the last tag is v0.2.0"):
            R.decide("v0.2.0", "0.2.5", None, self.FEAT)

    def test_a_release_prepared_and_not_tagged_is_folded_into(self):
        plan = R.decide("v0.2.0", "0.2.1", "0.2.1", self.FEAT)
        self.assertEqual((plan.version, plan.folded, plan.computed), ("0.2.1", True, "0.3.0"))
        self.assertEqual(R.decide("v0.2.0", "0.2.1", "0.2.1", self.FEAT, "0.2.1").version, "0.2.1")
        with self.assertRaisesRegex(R.Refused, "0.2.1 is prepared and not tagged"):
            R.decide("v0.2.0", "0.2.1", "0.2.1", self.FEAT, "0.3.0")
        with self.assertRaisesRegex(R.Refused, r"untagged, and Cargo.toml says 0.2.0"):
            R.decide("v0.2.0", "0.2.0", "0.2.1", self.FEAT)

    def test_with_no_tag_yet_the_first_is_the_workspaces_version(self):
        plan = R.decide(None, "0.1.0", None, self.FEAT)
        self.assertEqual((plan.version, plan.level), ("0.1.0", "first"))

    def test_the_section_under_unreleased_is_pending_only_untagged(self):
        self.assertEqual(R.pending_section(CHANGELOG, lambda v: False), "0.3.0")
        self.assertIsNone(R.pending_section(CHANGELOG, lambda v: v == "0.3.0"))
        released = CHANGELOG.replace("## [0.3.0] - 2026-10-06\n\nThe release, in a paragraph.\n\n### Fixed: a thing\n\n- **It works.**\n\n", "")
        self.assertIsNone(R.pending_section(released, lambda v: v == "0.2.0"))


# ─── the bump ────────────────────────────────────────────────────────────────


class TheBump(unittest.TestCase):
    def test_writes_every_place_the_workspaces_version_is_and_nothing_else(self):
        with Tree() as t:
            before = {rel: t.text(rel) for rel in ("Cargo.toml", "crates/auracle-a/Cargo.toml", "crates/auracle-b/Cargo.toml", "Cargo.lock")}
            changed = R.bump(t.root, "0.3.0")
            self.assertEqual(
                [(p.rel, p.line + 1) for p in changed],
                [("Cargo.toml", 9), ("Cargo.toml", 17), ("crates/auracle-b/Cargo.toml", 6), ("Cargo.lock", 6), ("Cargo.lock", 13)],
            )
            for rel, text in before.items():
                was, now = text.split("\n"), t.text(rel).split("\n")
                moved = [i + 1 for i, (a, b) in enumerate(zip(was, now)) if a != b]
                self.assertEqual(moved, [p.line + 1 for p in changed if p.rel == rel], rel)
                for i in moved:
                    self.assertEqual(now[i - 1], was[i - 1].replace('"0.2.0"', '"0.3.0"'))
            # quiver-dsp, fugue, the commented-out line and the registry's
            # crate of the same name as a member keep 0.2.0.
            self.assertIn('quiver-dsp = "0.2.0"', t.text("Cargo.toml"))
            self.assertIn('# auracle-b = { path = "crates/auracle-b", version = "0.2.0" }', t.text("Cargo.toml"))
            self.assertIn('fugue = { version = "0.2.0"', t.text("crates/auracle-b/Cargo.toml"))
            self.assertEqual(t.text("Cargo.lock").count('version = "0.2.0"'), 2)

    def test_at_the_version_already_writes_nothing(self):
        with Tree() as t:
            R.bump(t.root, "0.3.0")
            lock = t.text("Cargo.lock")
            self.assertEqual(R.bump(t.root, "0.3.0"), [])
            self.assertEqual(t.text("Cargo.lock"), lock)

    def test_a_bump_half_made_by_hand_is_refused_and_nothing_written(self):
        with Tree() as t:
            t.write("crates/auracle-b/Cargo.toml", CRATE_B.replace('version = "0.2.0" }', 'version = "0.2.1" }', 1))
            with self.assertRaisesRegex(R.Refused, r"crates/auracle-b/Cargo.toml:6: 0.2.1, and Cargo.toml's workspace says 0.2.0"):
                R.bump(t.root, "0.3.0")
            self.assertIn('version = "0.2.0"', t.text("Cargo.toml"))
            code, _, err = t.run("bump", "v0.3.0")
            self.assertEqual(code, 1)
            self.assertIn("`v0.3.0` is not a version", err)

    def test_the_command_says_where_it_wrote(self):
        with Tree() as t:
            code, out, _ = t.run("bump", "0.3.0")
            self.assertEqual(code, 0)
            self.assertIn("Cargo.lock:13: 0.2.0 -> 0.3.0", out)
            code, out, _ = t.run("bump", "0.3.0")
            self.assertIn("at 0.3.0 already", out)


class TheManifests(unittest.TestCase):
    """Read line by line, as Cargo writes them: a TOML parser is in Python's
    library from 3.11 only, and `make dev-check` may run on macOS's 3.9."""

    def test_a_key_is_read_in_its_own_table_only(self):
        text = (
            '[workspace]\nmembers = ["crates/a", "crates/b"] # two\n\n'
            '[workspace.package] # the shared keys\nrust-version = "1.87"\nversion = "0.2.0"  # the workspace\'s\n\n'
            '[workspace.dependencies]\nserde = { version = "1" }\n\n[profile.release]\nversion = "9.9.9"\n'
        )
        self.assertEqual(R.strings(text, "workspace", "members"), ["crates/a", "crates/b"])
        self.assertEqual(R.string(text, "workspace.package", "version"), (5, "0.2.0"))
        self.assertEqual(R.workspace_version(text), "0.2.0")
        self.assertEqual(R.workspace_version(text.replace('version = "0.2.0"', 'version.workspace = true')), "")

    def test_an_array_on_several_lines_leaves_its_comments_out(self):
        text = '[workspace]\nmembers = [\n    "crates/a",\n    # "crates/old",\n    "crates/b", # the last\n]\nexclude = ["x"]\n'
        self.assertEqual(R.strings(text, "workspace", "members"), ["crates/a", "crates/b"])
        self.assertEqual(R.strings(text, "workspace", "exclude"), ["x"])
        self.assertEqual(R.strings(text, "workspace.package", "members"), [])

    def test_a_crate_with_no_name_is_refused(self):
        with Tree() as t:
            t.write("crates/auracle-b/Cargo.toml", CRATE_B.replace('name = "auracle-b"\n', ""))
            with self.assertRaisesRegex(R.Refused, r"^crates/auracle-b/Cargo.toml: no `name` under `\[package\]`$"):
                R.bump(t.root, "0.3.0")
            self.assertEqual(R.verify(t.root, "v0.2.0"), ["crates/auracle-b/Cargo.toml: no `name` under `[package]`"])


# ─── what a tag owes ─────────────────────────────────────────────────────────


class TheTag(unittest.TestCase):
    def ready(self, t):
        R.bump(t.root, "0.3.0")

    def test_a_ready_tree_owes_nothing(self):
        with Tree() as t:
            self.ready(t)
            self.assertEqual(R.verify(t.root, "v0.3.0"), [])
            code, out, _ = t.run("verify", "v0.3.0")
            self.assertEqual(code, 0)
            self.assertIn("v0.3.0: the workspace, CHANGELOG.md and changelog.d/ are ready", out)

    def test_a_name_that_is_not_a_releases_tag(self):
        with Tree() as t:
            self.ready(t)
            for tag in ("main", "0.3.0", "v0.3", "v0.3.0-"):
                self.assertEqual(R.verify(t.root, tag), [f"`{tag}` is not a release's tag: vX.Y.Z"])
            # A pre-release's tag is one: it owes the same, at its version.
            self.assertIn("Cargo.toml:9: 0.3.0, not 0.3.0-rc.1", R.verify(t.root, "v0.3.0-rc.1")[0])

    def test_the_workspace_at_another_version_names_each_place(self):
        with Tree() as t:
            wrong = R.verify(t.root, "v0.3.0")
            self.assertEqual(len(wrong), 5)
            self.assertIn("Cargo.toml:9: 0.2.0, not 0.3.0", wrong[0])
            self.assertTrue(wrong[-1].startswith("Cargo.lock:13: 0.2.0, not 0.3.0"))

    def test_no_section_or_an_empty_one_is_refused(self):
        with Tree() as t:
            self.ready(t)
            t.write("CHANGELOG.md", CHANGELOG.replace("[0.3.0]", "[0.3.1]"))
            self.assertEqual(R.verify(t.root, "v0.3.0"), ["CHANGELOG.md: no `## [0.3.0]` section: a release with no notes is not a release"])
            t.write("CHANGELOG.md", CHANGELOG.replace("[0.3.0]", "[0.3.0.1]"))
            self.assertIn("no `## [0.3.0]` section", R.verify(t.root, "v0.3.0")[0])
            t.write("CHANGELOG.md", f"# Changelog\n\n## [Unreleased]\n\n{C.NOTE}\n\n## [0.3.0] - 2026-10-06\n\n## [0.2.0] - 2026-08-04\n\n- x\n")
            self.assertEqual(R.verify(t.root, "v0.3.0"), ["CHANGELOG.md: the `## [0.3.0]` section is empty"])

    def test_an_entry_left_waiting_is_refused(self):
        with Tree() as t:
            self.ready(t)
            t.write("changelog.d/late.md", "### Fixed: late\n\n- **Merged while the release PR waited.**\n")
            code, _, err = t.run("verify", "v0.3.0")
            self.assertEqual(code, 1)
            self.assertIn("changelog.d/ still holds entries that no release notes mention: changelog.d/late.md", err)
            self.assertIn("folds them into `## [0.3.0]`", err)

    def test_its_section_is_the_one_release_yml_cuts(self):
        self.assertEqual(R.section(CHANGELOG, "0.3.0"), "The release, in a paragraph.\n\n### Fixed: a thing\n\n- **It works.**")
        self.assertEqual(R.section(CHANGELOG, "0.2.0"), "### Added: the rest\n\n- **More.**")


# ─── the notes ───────────────────────────────────────────────────────────────


class TheNotes(unittest.TestCase):
    def test_every_type_pr_checks_accepts_has_one_group_or_is_left_out(self):
        grouped = [k for _, kinds in R.GROUPS for k in kinds] + list(R.LEFT_OUT)
        self.assertEqual(sorted(grouped), sorted(P.TYPES))

    def test_by_type_oldest_first_the_release_pr_left_out(self):
        newest_first = [
            R.read_subject("release: 0.3.0 (#9)"),
            R.read_subject("fix(web): second fix (#8)"),
            R.read_subject("The old style of title (#7)"),
            R.read_subject("tests: one (#6)"),
            R.read_subject("feat!: the big one (#5)"),
            R.read_subject("test: two (#4)"),
            R.read_subject("fix: first fix (#3)"),
            R.read_subject("docs: pushed by hand", "A Person"),
        ]
        who = {8: "ann", 7: "bob", 6: "ann", 5: "cy", 4: "dependabot[bot]", 3: "bob"}
        text = R.render(newest_first, who, "v0.2.0")
        self.assertEqual(
            text,
            "## Merged since v0.2.0\n\n"
            "7 pull requests, by type. Contributors: A Person, @bob, @dependabot[bot], @cy, @ann.\n\n"
            "### Features\n\n- feat!: the big one (#5) by @cy\n\n"
            "### Fixes\n\n- fix: first fix (#3) by @bob\n- fix(web): second fix (#8) by @ann\n\n"
            "### Documentation\n\n- docs: pushed by hand by A Person\n\n"
            "### Tests\n\n- test: two (#4) by @dependabot[bot]\n- tests: one (#6) by @ann\n\n"
            "### Without a type\n\n- The old style of title (#7) by @bob\n",
        )
        self.assertNotIn("## [", text)

    def test_the_authors_come_a_page_at_a_time_until_below_the_lowest_wanted(self):
        api = Api(250)
        got = R.authors([250, 160, 130], api)
        self.assertEqual(got, {250: "user1", 160: "user1", 130: "user1"})
        self.assertEqual(len(api.calls), 2)
        self.assertTrue(all("state=closed" in c and "direction=desc" in c for c in api.calls))

    def test_one_the_pages_never_showed_is_asked_for_alone(self):
        # 130 isn't among the closed PRs' pages (a PR that was reopened, say):
        # the third page reaches below it, so the fourth is never read, and
        # 130 is asked for on its own.
        api = Api(350, missing={130})
        got = R.authors([300, 130], api)
        self.assertEqual(got, {300: "user0", 130: "user1"})
        self.assertEqual([c.rsplit("page=", 1)[-1] for c in api.calls[:3]], ["1", "2", "3"])
        self.assertEqual(api.calls[3:], [f"repos/{R.REPO}/pulls/130"])

    def test_an_app_and_a_deleted_account(self):
        self.assertEqual(R.login({"login": "dependabot[bot]", "type": "Bot"}), "dependabot[bot]")
        self.assertEqual(R.login(None), "ghost")
        self.assertEqual(R.authors([], refuse_network), {})

    def test_the_notes_ask_only_for_the_prs_they_list(self):
        api = Api(12)
        text = R.notes(titles("release: 0.3.0 (#12)", "fix: a (#11)", "PATCH: b (#10)"), "v0.2.0", api)
        self.assertIn("- fix: a (#11) by @user2", text)
        self.assertIn("- PATCH: b (#10) by @user1", text)
        self.assertNotIn("#12", text)


class TheReleasePr(unittest.TestCase):
    def plan(self, folded=False):
        if folded:
            return R.decide("v0.2.0", "0.2.1", "0.2.1", titles("feat: a (#3)", "PATCH: b (#2)"))
        return R.decide("v0.2.0", "0.2.0", None, titles("feat: a (#3)", "fix: c (#4)", "PATCH: b (#2)"))

    def test_its_title_and_body_pass_pr_checks(self):
        for folded in (False, True):
            plan = self.plan(folded)
            self.assertEqual(P.check_title(f"release: {plan.version}"), [])
            links = P.parse(R.body(plan, 3, "https://github.com/o/r/actions/runs/1"))
            self.assertEqual((links.closes, links.refs, links.problems), ([], [], []))
            self.assertEqual(links.no_issue, f"the {plan.version} release")

    def test_it_says_the_version_and_why_and_what_the_operator_does(self):
        text = R.body(self.plan(), 1)
        self.assertIn("**The version:** 0.3.0, from v0.2.0: 1 feat.", text)
        self.assertIn("with the one entry that waited", text)
        self.assertIn("and what `[Unreleased]` held", text)
        self.assertIn("**The bump:** the workspace's version in `Cargo.toml`", text)
        self.assertIn("1. Write the paragraph under `## [0.3.0]`", text)
        self.assertIn("With nothing to write, close the PR", text)
        self.assertIn("read what it holds before that push", text)
        self.assertIn("Titles merged since v0.2.0, by type: feat 1, fix 1, without a type 1.", text)
        self.assertIn("push it to this branch. That push starts `CI` and `PR checks`", text)
        self.assertIn("close the PR and reopen it", text)
        self.assertIn("`@mergifyio queue`", text)
        self.assertIn("tags its merge commit `v0.3.0`", text)

    def test_a_fold_says_so_and_claims_no_bump_or_new_paragraph(self):
        text = R.body(self.plan(folded=True), 2)
        self.assertIn("**The version:** 0.2.1, prepared before and not tagged", text)
        self.assertIn("the titles since v0.2.0 alone would make 0.3.0", text)
        self.assertIn("the 2 entries that waited in `changelog.d/` (now deleted), folded into the top of `## [0.2.1]`", text)
        self.assertIn("Its heading and paragraph are as they were.", text)
        self.assertIn("**The bump:** none. The workspace is at 0.2.1 already", text)
        self.assertIn("1. Check the paragraph under `## [0.2.1]` still says what this release is", text)
        self.assertIn("With nothing to change, close the PR and reopen it", text)
        for claim in ("`Cargo.lock`", "`[Unreleased]` held", "Write the paragraph"):
            self.assertNotIn(claim, text)

    def test_its_commit_message_says_what_it_holds(self):
        made = R.message(self.plan())
        self.assertTrue(made.startswith("release: 0.3.0\n\nThe version and the changelog's section for 0.3.0"), made)
        self.assertIn("Cargo.lock", made)
        self.assertTrue(all(len(line) <= 72 for line in made.split("\n")), made)
        fold = R.message(self.plan(folded=True))
        self.assertTrue(fold.startswith("release: 0.2.1\n\nThe entries that merged after 0.2.1 was prepared"), fold)
        self.assertIn("nothing is bumped", fold)
        for claim in ("Cargo.lock", "[Unreleased]", "follows, by hand"):
            self.assertNotIn(claim, fold)


# ─── the command, on a scratch repository ────────────────────────────────────


class TheHistory(unittest.TestCase):
    def history(self, t):
        """v0.1.0 on a feat, v0.1.1 on a fix and a docs change, a v0.9.0 on
        a branch main never merged, then a breaking fix and an untyped title
        waiting; the workspace at 0.1.1."""
        t.write("Cargo.toml", CARGO.replace('"0.2.0"', '"0.1.1"'))
        t.write("CHANGELOG.md", f"# Changelog\n\n## [Unreleased]\n\n{C.NOTE}\n\n## [0.1.1] - 2026-01-02\n\n- x\n")
        t.commit("feat: a (#1)")
        t.git("tag", "-a", "v0.1.0", "-m", "v0.1.0")
        t.commit("fix(web): b (#2)")
        t.commit("docs: c (#3)")
        t.git("tag", "v0.1.1")
        t.git("checkout", "-q", "-b", "side")
        t.commit("feat: never merged (#4)")
        t.git("tag", "v0.9.0")
        t.git("checkout", "-q", "main")
        t.commit("fix!: d (#5)")
        t.commit("PATCH: e (#6)")

    def test_plans_from_the_last_tag_main_has(self):
        with Tree(git=True) as t:
            self.history(t)
            out_file = t.root / "out"
            out_file.write_text("")
            body, message = t.root / "body.md", t.root / "message"
            with mock.patch.dict(os.environ, {"GITHUB_OUTPUT": str(out_file)}):
                code, out, err = t.run("plan", "--github-output", "--body", str(body), "--message", str(message))
            self.assertEqual(code, 0, err)
            self.assertIn("release: 0.2.0", out)
            self.assertIn("a minor bump from v0.1.1: 1 breaking (`!`), which moves the minor while the major is 0", out)
            self.assertIn("2 merged since v0.1.1: fix 1, without a type 1", out)
            self.assertIn("    PATCH: e (#6)", out)
            self.assertEqual(out_file.read_text(), "version=0.2.0\nprevious=v0.1.1\nfolded=false\n")
            self.assertIn("No issue: the 0.2.0 release", body.read_text())
            self.assertIn("with the 0 entries that waited", body.read_text())
            self.assertTrue(message.read_text().startswith("release: 0.2.0\n\nThe version and the changelog's section for 0.2.0"))

    def test_a_late_entry_folds_into_the_untagged_release_and_bumps_nothing(self):
        with Tree(git=True) as t:
            self.history(t)
            # The release PR for 0.2.0 merged and its tag was refused; an entry
            # merged after it.
            t.write("Cargo.toml", CARGO)
            t.write("CHANGELOG.md", f"# Changelog\n\n## [Unreleased]\n\n{C.NOTE}\n\n## [0.2.0] - 2026-02-03\n\nThe paragraph.\n\n- y\n\n## [0.1.1] - 2026-01-02\n\n- x\n")
            t.commit("release: 0.2.0 (#7)")
            t.write("changelog.d/late.md", "### Fixed: late\n\n- **Late.**\n")
            t.commit("fix: late (#8)")
            out_file, body, message = t.root / "out", t.root / "body.md", t.root / "message"
            out_file.write_text("")
            with mock.patch.dict(os.environ, {"GITHUB_OUTPUT": str(out_file)}):
                code, out, err = t.run("plan", "--github-output", "--body", str(body), "--message", str(message))
            self.assertEqual(code, 0, err)
            self.assertIn("folded into 0.2.0, prepared and not tagged", out)
            self.assertEqual(out_file.read_text(), "version=0.2.0\nprevious=v0.1.1\nfolded=true\n")
            self.assertIn("**The bump:** none. The workspace is at 0.2.0 already", body.read_text())
            self.assertIn("the one entry that waited in `changelog.d/` (now deleted), folded into the top of `## [0.2.0]`", body.read_text())
            self.assertIn("nothing is bumped", message.read_text())
            self.assertEqual(t.run("bump", "0.2.0")[1], "  the workspace is at 0.2.0 already: nothing to bump\n")

    def test_the_entries_waiting_are_counted_where_the_plan_reads(self):
        with Tree(git=True) as t:
            self.history(t)
            t.write("changelog.d/one.md", "### Fixed: one\n\n- **One.**\n")
            t.commit("fix: one (#7)")
            t.write("changelog.d/two.md", "### Fixed: two\n\n- **Two, not committed.**\n")
            body = t.root / "body.md"
            self.assertEqual(t.run("plan", "--body", str(body))[0], 0)
            self.assertIn("with the 2 entries that waited", body.read_text())
            self.assertEqual(t.run("plan", "--ref", "HEAD", "--body", str(body))[0], 0)
            self.assertIn("with the one entry that waited", body.read_text())
            self.assertEqual(t.run("plan", "--ref", "HEAD~1", "--body", str(body))[0], 0)
            self.assertIn("with the 0 entries that waited", body.read_text())

    def test_the_notes_for_a_tag_run_from_the_release_before_it(self):
        with Tree(git=True) as t:
            self.history(t)
            api = Api(6, who=lambda n: {"login": "ann"})
            code, out, err = t.run("notes", "v0.1.1", get=api)
            self.assertEqual(code, 0, err)
            self.assertTrue(out.startswith("## Merged since v0.1.0\n\n2 pull requests"))
            self.assertIn("- fix(web): b (#2) by @ann", out)
            self.assertIn("- docs: c (#3) by @ann", out)
            self.assertNotIn("(#1)", out)
            code, out, _ = t.run("notes", "--to", "HEAD", get=api)
            self.assertTrue(out.startswith("## Merged since v0.1.1\n"))
            self.assertIn("- fix!: d (#5) by @ann", out)
            self.assertNotIn("never merged", out)

    def test_a_ref_is_read_as_it_was_there(self):
        with Tree(git=True) as t:
            self.history(t)
            t.git("tag", "v0.2.0")
            # The tree moves on; the plan at the old tip reads that tip's
            # files and history, not the tree's.
            t.write("Cargo.toml", CARGO)
            t.commit("feat: f (#7)")
            code, out, err = t.run("plan", "--ref", "HEAD~1")
            self.assertEqual(code, 1)
            self.assertIn("nothing has merged since v0.2.0", err)
            code, out, err = t.run("plan")
            self.assertEqual(code, 0, err)
            self.assertIn("release: 0.3.0", out)

    def test_a_changelog_it_cannot_read_is_refused_in_one_line(self):
        with Tree(git=True) as t:
            self.history(t)
            t.write("CHANGELOG.md", t.text("CHANGELOG.md").replace("## [Unreleased]", "## Unreleased"))
            t.commit("fix: f (#7)")
            code, out, err = t.run("plan")
            self.assertEqual((code, out), (1, ""))
            self.assertEqual(err, "  CHANGELOG.md: 0 `## [Unreleased]` headings, not one\n")

    def test_notes_takes_a_tag_or_a_ref(self):
        with Tree(git=True) as t:
            self.history(t)
            with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit):
                t.run("notes")
            code, _, err = t.run("notes", "main")
            self.assertEqual(code, 1)
            self.assertIn("`main` is not a release's tag", err)


# ─── the real workspace ──────────────────────────────────────────────────────


class TheRealWorkspace(unittest.TestCase):
    FILES = ["Cargo.toml", "Cargo.lock"] + [str(p.relative_to(R.ROOT)) for p in sorted(R.ROOT.glob("crates/*/Cargo.toml"))]

    def test_every_place_agrees_on_one_version(self):
        found = R.places(R.ROOT)
        self.assertEqual({p.version for p in found}, {found[0].version}, found)
        self.assertEqual(found[0].rel, "Cargo.toml")

    def test_a_bump_moves_the_workspace_and_its_lock_and_nothing_else(self):
        tmp = pathlib.Path(tempfile.mkdtemp(prefix="release-real-", dir=TMP))
        try:
            for rel in self.FILES:
                (tmp / rel).parent.mkdir(parents=True, exist_ok=True)
                shutil.copy(R.ROOT / rel, tmp / rel)
            crates = R.members(tmp)
            changed = R.bump(tmp, "9.9.9")
            # The workspace's own, each pinned path dependency between its
            # crates, and each crate's entry in the lock.
            self.assertEqual(sum(1 for p in changed if p.rel == "Cargo.lock"), len(crates))
            self.assertEqual(R.verify(tmp, "v9.9.9")[:1], ["CHANGELOG.md: no `## [9.9.9]` section: a release with no notes is not a release"])
            self.assertEqual({p.version for p in R.places(tmp)}, {"9.9.9"})
            for rel in self.FILES:
                was = (R.ROOT / rel).read_text(encoding="utf-8").split("\n")
                now = (tmp / rel).read_text(encoding="utf-8").split("\n")
                moved = sum(1 for a, b in zip(was, now) if a != b)
                self.assertEqual((len(was), moved), (len(now), sum(1 for p in changed if p.rel == rel)), rel)
        finally:
            shutil.rmtree(tmp)


if __name__ == "__main__":
    # One line when they pass, like the rest of `make dev-check`; everything
    # unittest says when one fails.
    out = io.StringIO()
    result = unittest.TextTestRunner(stream=out, verbosity=2).run(unittest.defaultTestLoader.loadTestsFromModule(sys.modules[__name__]))
    if not result.wasSuccessful():
        sys.stderr.write(out.getvalue())
        sys.exit(1)
    print(f"  release tests: {result.testsRun} passed")
